### ISSUE TITLE
Jinja templating for your config file

### ISSUE THREAD

**Issue by rodluger** [katiebreivik/Z-dependent-DWDs#3]
@katiebreivik Check out https://showyourwork.readthedocs.io/en/stable/custom/#many-many-dependencies.
This could help simplify your ``showyourwork.yml`` file. Happy to chat about it / implement it for you if you're interested.

**Comment by katiebreivik** [comment]
AMAZING! I had my fingers crossed this would be coming in soon. Just working on pipeline stuff behind the scenes to get it all working. I'll let you know if I have questions along the way!

**Comment by katiebreivik** [comment]
fixed by previous commits!
